HEADER_BITS = 24
PREFIX_BITS = 16
VERSION_BITS = 8
MAX_CALLBACK_LENGTH = 64
MAX_PAYLOAD_BITS = 368

BIN_BITS_KEY = "bin_bits"
BIN_ORDER_KEY = "bin_order"
BIN_SIGNED_KEY = "bin_signed"

DEFAULT_BOOL_BITS = 1
DEFAULT_INT_BITS = 32
