HEADER_BITS = 24
PREFIX_BITS = 16
VERSION_BITS = 8
MAX_CALLBACK_LENGTH = 64

BASE64_RADIX = 64
BASE93_RADIX = 93

MAX_TOTAL_BITS_BASE64 = (BASE64_RADIX ** MAX_CALLBACK_LENGTH).bit_length() - 1
MAX_TOTAL_BITS_BASE93 = (BASE93_RADIX ** MAX_CALLBACK_LENGTH).bit_length() - 1
MAX_PAYLOAD_BITS_BASE64 = MAX_TOTAL_BITS_BASE64 - HEADER_BITS
MAX_PAYLOAD_BITS_BASE93 = MAX_TOTAL_BITS_BASE93 - HEADER_BITS

BIN_BITS_KEY = "bin_bits"
BIN_ORDER_KEY = "bin_order"
BIN_SIGNED_KEY = "bin_signed"

DEFAULT_BOOL_BITS = 1
DEFAULT_INT_BITS = 32

BIN_PLAN_ATTR = "__bin_plan__"
