HEADER_BITS = 24
PREFIX_BITS = 16
VERSION_BITS = 8
MAX_CALLBACK_LENGTH = 64
BASE64_RAW_BYTE_GROUP = 3
BASE64_ENCODED_BYTE_GROUP = 4
MAX_RAW_BYTES = (MAX_CALLBACK_LENGTH * BASE64_RAW_BYTE_GROUP) // BASE64_ENCODED_BYTE_GROUP
MAX_TOTAL_BITS = MAX_RAW_BYTES * 8
MAX_PAYLOAD_BITS = MAX_TOTAL_BITS - HEADER_BITS

BIN_BITS_KEY = "bin_bits"
BIN_ORDER_KEY = "bin_order"
BIN_SIGNED_KEY = "bin_signed"

DEFAULT_BOOL_BITS = 1
DEFAULT_INT_BITS = 32
